
service: serverless-restapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

# add 5 function for CURD operation
functions: 
  create:
    handler: handler.create
    events:
      - http: 
          path: user-streams
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http: 
          path: user-streams/{userId}/{sessionId}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
      - http: 
          path: all-user-streams
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http: 
          path: user-streams/{userId}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http: 
          path: user-streams/{userId}
          method: delete
          cors: true
plugins:
- serverless-offline